export enum ErrorCode {
    INVALID_USERNAME = "INVALID_USERNAME",
    DUPLICATE_USERNAME = "DUPLICATE_USERNAME",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
    INVALID_PROTOCOL = "INVALID_PROTOCOL"
}